
const KEY="datingHQCRMv4";
const priorities=["A+","A","B+","B","C"];
const defaults={profiles:[
{id:crypto.randomUUID(),name:"Samanta",age:"",platform:"Tinder",location:"London",status:"Hot",priority:"A+",stage:"Messaging",warmth:"High",travel:"Upcoming trip",lastMessage:"Her latest reply needs a grounded response.",nextMove:"Acknowledge her answer naturally and avoid assumptions.",notes:"Highest current priority.",followUp:new Date().toISOString().slice(0,10),cover:"",attachments:[],timeline:[{date:new Date().toISOString().slice(0,10),type:"Message",details:"Latest reply received."}]},
{id:crypto.randomUUID(),name:"Mona",age:"45",platform:"WhatsApp",location:"",status:"Active",priority:"A",stage:"WhatsApp",warmth:"High",travel:"Long distance",lastMessage:"Conversation progressing.",nextMove:"Maintain momentum and move toward a meeting.",notes:"Strong engagement.",followUp:"",cover:"",attachments:[],timeline:[]},
{id:crypto.randomUUID(),name:"Jasmina",age:"",platform:"Tinder",location:"Melbourne / Adelaide",status:"Active",priority:"A",stage:"Messaging",warmth:"High",travel:"Upcoming trip",lastMessage:"Travel context shared.",nextMove:"Move toward WhatsApp when natural.",notes:"Relationship potential.",followUp:"",cover:"",attachments:[],timeline:[]}
],templates:[
{title:"WhatsApp transition",text:"You’re easier to talk to than most people on here. Let’s move this to WhatsApp — what’s your number?"},
{title:"Travel reconnect",text:"I’m back shortly. Let’s pick this up properly when I’m closer rather than leave it to the app."},
{title:"Direct date move",text:"We should test whether this works as well in person. Coffee or a drink this week?"}
]};
let state=JSON.parse(localStorage.getItem(KEY)||"null")||defaults;
let pendingCover="",pendingAttachments=[],pendingTimeline=[],editingId=null;
const $=s=>document.querySelector(s), esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function due(){const t=new Date().toISOString().slice(0,10);return state.profiles.filter(p=>p.followUp&&p.followUp<=t&&p.status!=="Archived")}
function ranked(){return [...state.profiles].filter(p=>p.status!=="Archived").sort((a,b)=>priorities.indexOf(a.priority)-priorities.indexOf(b.priority))}
function card(p){return `<article class="card profile-card">
<div class="cover" ${p.cover?`style="background-image:url('${p.cover}')"`:""}><h3>${esc(p.name)}<small>${esc((p.age?p.age+" · ":"")+p.location)}</small></h3></div>
<div class="profile-body"><div class="row"><span class="badge ${esc(p.status)}">${esc(p.status)}</span><strong>${esc(p.priority)}</strong></div>
<p>${esc(p.stage)} · ${esc(p.platform)} · ${esc(p.travel||"None")}</p><p><strong>Next:</strong> ${esc(p.nextMove||"No next move")}</p>
<div class="row"><span>${esc(p.warmth)} warmth</span><div><button class="mini" onclick="openProfile('${p.id}')">Open</button> <button class="mini danger" onclick="removeProfile('${p.id}')">Delete</button></div></div></div></article>`}
function renderDashboard(){const p=ranked()[0], d=due();$("#dashboard").innerHTML=`
<div class="metrics">${["Hot","Active","Waiting"].map(s=>`<div class="card metric"><b>${state.profiles.filter(p=>p.status===s).length}</b><span>${s}</span></div>`).join("")}<div class="card metric"><b>${d.length}</b><span>Due today</span></div></div>
<div class="section-head"><h2>Top priority</h2><small>Front and centre</small></div>${p?`<div class="profile-grid">${card(p)}</div>`:`<div class="empty">No active profiles</div>`}
<div class="section-head"><h2>Needs attention</h2><small>${d.length} due</small></div><div class="profile-grid">${d.length?d.map(card).join(""):`<div class="empty">Nothing due today</div>`}</div>
<div class="section-head"><h2>Travel opportunities</h2><small>Current and upcoming</small></div><div class="profile-grid">${state.profiles.filter(p=>["Current city","Upcoming trip"].includes(p.travel)).map(card).join("")||`<div class="empty">No travel-linked profiles</div>`}</div>`}
function renderProfiles(q=""){const list=state.profiles.filter(p=>[p.name,p.location,p.platform,p.notes,p.stage].join(" ").toLowerCase().includes(q.toLowerCase()));$("#profiles").innerHTML=`<div class="profile-grid">${list.map(card).join("")||`<div class="empty">No profiles found</div>`}</div>`}
function renderPipeline(){const sts=["Hot","Active","Waiting","Dormant","Archived"];$("#pipeline").innerHTML=`<div class="pipeline-board">${sts.map(s=>`<div class="lane" data-status="${s}" ondragover="event.preventDefault();this.classList.add('dragover')" ondragleave="this.classList.remove('dragover')" ondrop="dropCard(event,'${s}')"><h3>${s}<span>${state.profiles.filter(p=>p.status===s).length}</span></h3>${state.profiles.filter(p=>p.status===s).map(p=>`<div class="card lane-card" draggable="true" ondragstart="event.dataTransfer.setData('text/plain','${p.id}')"><div class="lane-cover" ${p.cover?`style="background-image:url('${p.cover}')"`:""}></div><div class="lane-body"><h4>${esc(p.name)}</h4><p>${esc(p.priority)} · ${esc(p.stage)}</p><p>${esc(p.nextMove||"No next move")}</p></div></div>`).join("")}</div>`).join("")}</div>`}
window.dropCard=(e,status)=>{e.preventDefault();document.querySelectorAll(".lane").forEach(x=>x.classList.remove("dragover"));const p=state.profiles.find(x=>x.id===e.dataTransfer.getData("text/plain"));if(p){p.status=status;save()}}
function renderActions(){const d=due();$("#actions").innerHTML=`<div class="action-list">${d.map(p=>`<div class="card action"><input type="checkbox" onchange="complete('${p.id}')"><strong>${esc(p.name)}</strong><span>${esc(p.nextMove)}</span><span>${esc(p.followUp)}</span><button class="mini" onclick="openProfile('${p.id}')">Open</button></div>`).join("")||`<div class="empty">No actions due</div>`}</div>`}
window.complete=id=>{const p=state.profiles.find(x=>x.id===id);if(p){p.followUp="";save()}}
function renderTemplates(){$("#templates").innerHTML=`<div class="template-grid">${state.templates.map(t=>`<div class="card template"><h3>${esc(t.title)}</h3><p>${esc(t.text)}</p><button class="mini" onclick='navigator.clipboard.writeText(${JSON.stringify(t.text)})'>Copy</button></div>`).join("")}</div>`}
function renderSettings(){$("#settings").innerHTML=`<div class="settings-grid"><div class="card"><h3>Private local storage</h3><p>Your profiles, cover photos, attachments and timeline stay in this browser.</p></div><div class="card"><h3>Backups</h3><p>Export regularly. The JSON backup contains the full CRM including images.</p></div><div class="card"><h3>Cloud sync</h3><p>Not included in this local-only build. It requires a secure hosted backend and login.</p></div><div class="card"><h3>Install</h3><p>Host over HTTPS, open in Safari, then Share → Add to Home Screen.</p></div></div>`}
function renderAll(){renderDashboard();renderProfiles($("#search").value);renderPipeline();renderActions();renderTemplates();renderSettings()}
function switchView(v){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));$("#"+v).classList.add("active");document.querySelector(`[data-view="${v}"]`).classList.add("active");const m={dashboard:["Dashboard","What needs your attention now."],profiles:["Profiles","Cover shots, notes, timelines and attachments."],pipeline:["Pipeline","Drag profiles between stages."],actions:["Today","Your follow-up queue."],templates:["Templates","Reusable message formats."],settings:["Settings","Storage, backup and installation."]}[v];$("#title").textContent=m[0];$("#subtitle").textContent=m[1]}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>switchView(b.dataset.view));
function updateCover(){const e=$("#coverPreview");e.style.backgroundImage=pendingCover?`url('${pendingCover}')`:"";e.innerHTML=pendingCover?"":"<span>Cover photo</span>"}
function updateAttachments(){$("#attachmentsPreview").innerHTML=pendingAttachments.map((a,i)=>`<div class="attachment"><img src="${a}"><button type="button" onclick="deleteAttachment(${i})">×</button></div>`).join("")}
window.deleteAttachment=i=>{pendingAttachments.splice(i,1);updateAttachments()}
function updateTimeline(){$("#timelineEditor").innerHTML=pendingTimeline.sort((a,b)=>b.date.localeCompare(a.date)).map((e,i)=>`<div class="timeline-item"><strong>${esc(e.date)}</strong><span>${esc(e.type)}</span><span>${esc(e.details)}</span><button type="button" class="mini danger" onclick="deleteTimeline(${i})">×</button></div>`).join("")||`<div class="empty">No timeline events</div>`}
window.deleteTimeline=i=>{pendingTimeline.splice(i,1);updateTimeline()}
window.openProfile=id=>{const p=state.profiles.find(x=>x.id===id);editingId=id||null;$("#profileForm").reset();pendingCover=p?.cover||"";pendingAttachments=[...(p?.attachments||[])];pendingTimeline=[...(p?.timeline||[])];$("#dialogTitle").textContent=p?`Edit ${p.name}`:"Add profile";$("#profileId").value=p?.id||"";["name","age","platform","location","status","priority","stage","warmth","travel","followUp","lastMessage","nextMove","notes"].forEach(k=>{if(p)$("#"+k).value=p[k]||""});updateCover();updateAttachments();updateTimeline();$("#profileDialog").showModal()}
window.removeProfile=id=>{if(confirm("Delete this profile?")){state.profiles=state.profiles.filter(p=>p.id!==id);save()}}
$("#addBtn").onclick=()=>openProfile();$("#closeProfile").onclick=$("#cancelProfile").onclick=()=>$("#profileDialog").close();
$("#coverInput").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{pendingCover=r.result;updateCover()};r.readAsDataURL(f)}
$("#attachmentsInput").onchange=e=>[...e.target.files].forEach(f=>{const r=new FileReader();r.onload=()=>{pendingAttachments.push(r.result);updateAttachments()};r.readAsDataURL(f)})
$("#removeCover").onclick=()=>{pendingCover="";updateCover()}
$("#addTimeline").onclick=()=>{$("#timelineForm").reset();$("#eventDate").value=new Date().toISOString().slice(0,10);$("#timelineDialog").showModal()}
$("#closeTimeline").onclick=$("#cancelTimeline").onclick=()=>$("#timelineDialog").close();
$("#timelineForm").onsubmit=e=>{e.preventDefault();pendingTimeline.push({date:$("#eventDate").value,type:$("#eventType").value,details:$("#eventDetails").value});updateTimeline();$("#timelineDialog").close()}
$("#profileForm").onsubmit=e=>{e.preventDefault();const p={id:$("#profileId").value||crypto.randomUUID(),cover:pendingCover,attachments:pendingAttachments,timeline:pendingTimeline};["name","age","platform","location","status","priority","stage","warmth","travel","followUp","lastMessage","nextMove","notes"].forEach(k=>p[k]=$("#"+k).value);const i=state.profiles.findIndex(x=>x.id===p.id);if(i>=0)state.profiles[i]=p;else state.profiles.unshift(p);$("#profileDialog").close();save()}
$("#search").oninput=e=>{switchView("profiles");renderProfiles(e.target.value)}
$("#exportBtn").onclick=()=>{const b=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="dating-hq-crm-v4-backup.json";a.click();URL.revokeObjectURL(a.href)}
$("#importInput").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();alert("Imported")}catch{alert("Invalid backup")}};r.readAsText(f)}
renderAll();
